Server:
  RunMode: debug
  HttpPort: 8081
  ReadTimeout: 60
  WriteTimeout: 60
APP:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DbType: mysql
  UserName: root
  Password: 123456
  Host: localhost
  DBName: blog
  TablePrefix:
  Charset: utf8mb4
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: test
  Issuer: gin-blog
  Expire: 7200

